# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r

r:
  - release
  - oldrel
  
cache: packages

dist: xenial

os: linux

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()